name: Testing

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  pytest:
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out code from GitHub
        uses: "actions/checkout@v6"
      - name: Setup Python
        uses: "actions/setup-python@v5.5.0"
        with:
          python-version-file: ".python-version"
          cache: "pip"
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Tests suite
        run: |
          pytest \
            --timeout=9 \
            --durations=10 \
            -n auto \
            -p no:sugar \
            tests
